name: Minireq
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]  #[ubuntu-18.04, windows-2019, macos-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install pnpm (Linux)
        run: sudo npm install --global pnpm
        if: matrix.os == 'ubuntu-18.04'

      - name: Install pnpm (Windows)
        run: npm install --global pnpm
        if: matrix.os == 'windows-2019'

      - name: Cache dependencies
        uses: actions/cache@v1
        id: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: cd minireq && pnpm install

      - name: Build project
        run: cd minireq && pnpm run build

      - name: Run tests
        run: cd minireq && pnpm test

      - name: Upload coverage
        uses: codecov/codecov-action@v1
