name: Documentation
on:
  push:
    paths:
      - 'src/**'
      - 'README.md'
      - '.github/workflows/docs.yml'

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install pnpm
        run: sudo npm install --global pnpm

      - name: Cache dependencies
        uses: actions/cache@v1
        id: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          key: docs-pnpm-store-${{ hashFiles('package.json') }}
          restore-keys: |
            docs-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build documentation
        run: pnpm run docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
